import StyledJsxRegistry from '../shared/lib/registry';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import 'normalize.css';
import './globals.css';

import { HeaderLayout } from '@/shared/ui/layouts/header-layout';
import { FooterLayout } from '@/shared/ui/layouts/footer-layout';

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Next App Users',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.variable}`}>
        <StyledJsxRegistry>
          <HeaderLayout logo='POSTS APP' />
          <main>{children}</main>
          <FooterLayout text='Copyright 2024 All rights reserved' />
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
